package com.drink.daogen;

import com.drink.model.MemberLevel;
import java.util.List;

public interface MemberLevelMapperGen {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_level
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_level
     *
     * @mbggenerated
     */
    int insert(MemberLevel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_level
     *
     * @mbggenerated
     */
    MemberLevel selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_level
     *
     * @mbggenerated
     */
    List<MemberLevel> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_level
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MemberLevel record);
}