package com.drink.daogen;

import com.drink.model.Reward;
import java.util.List;

public interface RewardMapperGen {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward
     *
     * @mbggenerated
     */
    int insert(Reward record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward
     *
     * @mbggenerated
     */
    Reward selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward
     *
     * @mbggenerated
     */
    List<Reward> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Reward record);
}