package com.drink.daogen;

import com.drink.model.ThreeMember;
import java.util.List;

public interface ThreeMemberMapperGen {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table three_member
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table three_member
     *
     * @mbggenerated
     */
    int insert(ThreeMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table three_member
     *
     * @mbggenerated
     */
    ThreeMember selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table three_member
     *
     * @mbggenerated
     */
    List<ThreeMember> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table three_member
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ThreeMember record);
}