package com.drink.daogen;

import com.drink.model.ThreeReward;
import java.util.List;

public interface ThreeRewardMapperGen {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table three_reward
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table three_reward
     *
     * @mbggenerated
     */
    int insert(ThreeReward record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table three_reward
     *
     * @mbggenerated
     */
    ThreeReward selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table three_reward
     *
     * @mbggenerated
     */
    List<ThreeReward> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table three_reward
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ThreeReward record);
}