(function(Raphael){var fi=1.6180339887;Raphael.progressbar=function(param){param=param||{};param=_extends(param,{raphael:null,value:1,minvalue:1,maxvalue:20,fixsize:{top:0,left:0},paperwidth:400,paperheight:400,size:200,size2:8,csize:15,csize2:40,padding:5,radius:1,linewidth:1,clinew:1,vertical:1,color:"#0099cb",backrect:null,cursors:null,frontrect:null,onchange:function(value){}});return new ProgressBar(param);};function ProgressBar(param){this._extends(param);this.init();if(!this.vertical){this.processHorizontal();}else{this.processVertical();}
    this.onchange&&this.onchange(this.val());};ProgressBar.prototype.init=function(){this.val(this.value);var raphael=this.getRaphael();};ProgressBar.prototype.processVertical=function(){var that=this;drawRect(that);drawCursor(that);var csize31=this.csize/3;var csize32=2*this.csize/3;this.minx=Math.round(this.x-csize31);this.maxx=Math.round(this.x+this.size-csize32);this.miny=Math.round(this.y-csize32);this.maxy=Math.round(this.y+this.size-csize32);this.setColor(this.color);};function drawRect(that){var h=that.size2;var bx=that.x;var by=that.y;var bw=that.size;var bh=that.size2;if(that.vertical){bw=that.size2;bh=that.size;}
    that.backrect=that.raphael.rect(bx,by,bw,bh).attr({stroke:"#fff",fill:"180-#fff-#000","stroke-width":that.linewidth});that.frontrect=that.backrect.clone().attr({stroke:"#0099cb",fill:"#0099cb",opacity:0,"stroke-width":that.linewidth});var style=that.frontrect.node.style;style.unselectable="on";style.MozUserSelect="none";style.WebkitUserSelect="none";that.frontrect.drag(function(dx,dy,_x,_y){that.docOnMove(dx,dy,_x,_y);},function(_x,_y){that.bOnTheMove=true;var dd=_x-that.x;if(that.vertical){dd=_y-that.y;}
        that.setB(dd);},function(){that.bOnTheMove=false;});}
    function drawCursor(that){var v=that.size*(that.value/(that.maxvalue-that.minvalue));var cx=that.x-that.padding;var cy=that.y-that.padding;var cw=that.size2/2;var ch=that.size2+2*that.padding;if(that.vertical){cy=cy+v;var cw=that.size2+2*that.padding;var ch=that.size2/2;}else{cx=cx+v;}
        that.cursors=that.raphael.set();that.cursors.push(that.raphael.rect(cx,cy,cw,ch,that.radius).attr({stroke:"#0099cb",fill:"#0099cb",opacity:.5,"stroke-width":that.linewidth}));that.cursors.push(that.cursors[0].clone().attr({stroke:"#80c4ee",opacity:1,"stroke-width":that.clinew}));};ProgressBar.prototype.getRaphael=function(){if(!this.raphael){if(this.element){this.raphael=Raphael(this.element,this.paperwidth,this.paperheight);}else{this.raphael=Raphael(this.x,this.y,this.paperwidth,this.paperheight);}}
        return this.raphael;};ProgressBar.prototype.processHorizontal=function(){this.processVertical();};ProgressBar.prototype.docOnMove=function(dx,dy,_x,_y){if(this.bOnTheMove){var dd=_x-this.x;if(this.vertical){dd=_y-this.y;}
        this.setB(dd);}};ProgressBar.prototype.setB=function(_dd){_dd=_dd-(this.vertical?this.fixsize.top:this.fixsize.left);var ratio=this.getRatio(_dd);var v=this.minvalue+Math.round((this.maxvalue-this.minvalue)*ratio);var dd=_dd-this.size2/2;var attrdd={};if(this.vertical){dd<this.miny&&(dd=this.miny);dd>this.maxy&&(dd=this.maxy);attrdd={y:dd};}else{dd<this.minx&&(dd=this.minx);dd>this.maxx&&(dd=this.maxx);attrdd={x:dd};}
        this.cursors.attr(attrdd);this.val(v);this.onchange&&this.onchange(this.val());};ProgressBar.prototype.getRatio=function(_dd){if(!this.vertical){_dd<this.minx&&(_dd=this.minx);_dd>this.maxx&&(_dd=this.maxx);var ratio=(_dd-this.minx)/(this.maxx-this.minx);}else{_dd<this.miny&&(_dd=this.miny);_dd>this.maxy&&(_dd=this.maxy);var ratio=(_dd-this.miny)/(this.maxy-this.miny);}
        return ratio;};ProgressBar.prototype.setColor=function(_color){this.backrect.attr({fill:_color});return this;};ProgressBar.prototype.refreshCursor=function(){var v=this.size*(this.value/(this.maxvalue-this.minvalue));var cx=Math.round(this.x-this.csize*4/3);var cy=Math.round(this.y-this.csize*4/3);var attrdd={};if(this.vertical){cy=cy+v;attrdd={y:cy};}else{cx=cx+v;attrdd={x:cx};}
        this.cursors&&this.cursors.attr(attrdd);}
    ProgressBar.prototype.val=function(value,quiet){if(0===arguments.length){return this.value;}
        if(value>this.maxvalue){value=this.maxvalue;}
        if(value<this.minvalue){value=this.minvalue;}
        this.value=value;this.refreshCursor();if(!quiet){this.onchange&&this.onchange(value);}
        return this;};ProgressBar.prototype.add=function(value,quiet){value=value||1;var v=this.val();this.val(v+value);return this;};ProgressBar.prototype.up=function(value,quiet){return this.add(1,quiet);};ProgressBar.prototype.down=function(value,quiet){return this.add(-1,quiet);};ProgressBar.prototype._extends=_extends;function _extends(obj1,obj2){if(!obj1){return false;}
        obj2=obj2||this;if(obj2===window){obj2={};}
        for(var name in obj1){if(obj1.hasOwnProperty(name)){var v=obj1[name];obj2[name]=v;}}
        return obj2;};})(window.Raphael);