[#ftl]
[#-- @implicitly included --]
[#-- @ftlvariable name="generatorData" type="com.innovation.cornerstone.rest.generator.data.GeneratorData" --]
[#-- @ftlvariable name="controllerData" type="com.innovation.cornerstone.rest.generator.data.ControllerData" --]
[#-- @ftlvariable name="actionData" type="com.innovation.cornerstone.rest.generator.data.ActionData" --]
[#-- @ftlvariable name="parameter" type="com.innovation.cornerstone.rest.generator.data.ParameterData" --]